# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c1252baf5451cd8da55eb251374ab380ce4e2d2d6bc9edf437e6ad9b83f09b38ef6eacb2ae862a1cea5f9b3df05932ebd959f08569eb2c044f7a71a17f4e47

test:
  secret_key_base: ae26ccb18e0aaf0f7c86e5b7abf703e089925a1d72b72e69b4af7dde28546891b9adc35ab90669990ffb8be07336887141f0db979b3d5fa34cb36c2d641dda90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
